---

- name: Install fcitx5, fcitx5-configtool, fcitx5-gtk, fcitx5-qt, fcitx5-chinese-addons, fcitx5-hangul, fcitx5-mozc
  pacman:
    name:
      - fcitx5
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-qt
      - fcitx5-chinese-addons
      - fcitx5-hangul
      - fcitx5-mozc
    state: present
  become: yes

- name: Copy fcitx5 config
  copy:
    src: fcitx5
    dest: "{{ ansible_user_dir }}/.config/"
