---

- name: Install firefox
  flatpak:
    name: org.mozilla.firefox
    state: present
  become: yes

- name: Override --socket=wayland --filesystem=home
  shell: flatpak override --socket=wayland --filesystem=home org.mozilla.firefox
  become: yes

- name: Set as default web browser
  shell: xdg-settings set default-web-browser org.mozilla.firefox.desktop

- name: Install xdg-desktop-portal-wlr
  pacman:
    name: xdg-desktop-portal-wlr
    state: present
  become: yes

- name: Configure user service environment variables
  copy:
    src: environment.d
    dest: "{{ ansible_user_dir }}/.config/"

# Hardware video acceleration
https://wiki.archlinux.org/title/firefox#Hardware_video_acceleration
