---

- name: Install foot
  shell: paru -S --needed --noconfirm foot || /bin/true

- name: Create $HOME/.config/foot directory if it does not exist
  file:
    path: "{{ ansible_user_dir }}/.config/foot"
    state: directory

- name: Copy foot config
  copy:
    src: foot.ini
    dest: "{{ ansible_user_dir }}/.config/foot/"
