---

- name: Install swayr
  shell: paru -S --needed --noconfirm swayr-git || /bin/true

- name: Create $HOME/.config/swayr directory if it does not exist
  file:
    path: "{{ ansible_user_dir }}/.config/swayr"
    state: directory

- name: Copy swayr config
  copy:
    src: swayr.toml
    dest: "{{ ansible_user_dir }}/.config/sway/config.toml"
