#!/usr/bin/sh

# fcitx5
# export CLUTTER_IM_MODULE=xim
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5      # for alacritty

# firefox
export MOZ_ENABLE_WAYLAND=1

# vaapi
# export LIBVA_DRIVER_NAME=iHD

# alacritty
export WINIT_UNIX_BACKEND=x11

# qt5
# export QT_QPA_PLATFORMTHEME=qt5ct

# flatpak
export XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share"

# grim
export GRIM_DEFAULT_DIR="$HOME/Pictures/grim"

exec sway
