#!/usr/bin/env ruby

require 'json'

def extract_containers(nodes)
  nodes.flat_map do |node|
    if %w[con floating_con].include?(node['type']) && node['pid']
      [node]
    else
      child_nodes = node.values_at('nodes', 'floating_nodes').flatten.compact
      extract_containers(child_nodes)
    end
  end
end

windows = nil
IO.popen('swaymsg -t get_tree') do |io|
  nodes = JSON.parse(io.read)['nodes']
  result = extract_containers(nodes).map do |container|
    name = "#{container['app_id'] || container['window_properties']['class']} - #{container['name']}"
    [container['id'], name]
  end
  windows = Hash[result]
end

IO.popen('wofi --dmenu --insensitive', 'r+') do |io|
  io.puts windows.values.join("\n")
  io.close_write
  selected = io.gets.chomp
  container_id = windows.key(selected)
  system("swaymsg [con_id=#{container_id}] focus")
end
