---

- name: Install neovim
  pacman:
    name:
      - neovim
      - lua-language-server
    state: present
  become: yes

- name: Config fish for neovim
  copy:
    src: fish/neovim.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish

- name: Copy neovim config
  copy:
    src: neovim/
    dest: "{{ ansible_user_dir }}/.config/nvim/"

- name: Install pynvim
  pip:
    name: pynvim
    extra_args: --user
    state: latest
