---

- name: Install starship
  pacman:
    name: starship
    state: present
  become: yes

- name: Config fish for starship
  copy:
    src: fish/starship.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish
